### ISSUE TITLE
The reference links in the generated report

### ISSUE THREAD

**Issue by eagr** [awslabs/duvet#64]
I noticed that the reference links we get from copying a requirement in the report relies on the target of `duvet extract`. Do you think that it's reasonable to decouple them?

The expected outcome would be executing `duvet extract` with a local file as target, but somehow being able to have urls pointing to specific sections of the desired spec in the generated report.

**Comment by camshaft** [comment]
We plan on introducing a config file to enumerate target aliases and canonical URLs. It would look something like:

```toml
[[compliance.spec.ietf]]
id = "quic-transport"
title = "QUIC: A UDP-Based Multiplexed and Secure Transport"
url = "https://www.rfc-editor.org/rfc/rfc9000.txt"
aliases = [
    "https://datatracker.ietf.org/doc/html/rfc9000",
    "https://www.rfc-editor.org/rfc/rfc9000.html"
]
```
